basePath: /api
definitions:
  errors.RestErr:
    properties:
      error:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  jobs.Job:
    properties:
      id:
        type: string
      input:
        type: string
      lastUpdated:
        type: string
      message:
        type: string
      output:
        type: string
      path:
        type: string
      slurmID:
        type: integer
      slurml:
        type: boolean
      status:
        type: string
    type: object
  jobs.Upload:
    properties:
      id:
        type: string
      input:
        type: string
      slurml:
        type: boolean
    type: object
info:
  contact: {}
  description: API for managing job queue in jobd application
  title: jobd (Job Daemon) API
  version: "1.0"
paths:
  /api/get/{id}:
    get:
      description: Fetches a job by its `id` (provided by the user) with partial content
        handling
      parameters:
      - description: Job ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved job
          schema:
            $ref: '#/definitions/jobs.Job'
        "206":
          description: Partially completed job
          schema:
            $ref: '#/definitions/jobs.Job'
        "404":
          description: Job not found
          schema:
            $ref: '#/definitions/errors.RestErr'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/errors.RestErr'
      summary: Retrieve a job from the queue
  /api/upload:
    post:
      consumes:
      - application/json
      description: Upload a payload. `id` is a unique user-provided job identificator.
        The `input` field must contain a base64 encoded`.zip` file with a `run.sh`
        script and the input data. `slurml` marks the job for redirection to the `slurml`
        endpoint (wip)
      parameters:
      - description: Job to be uploaded
        in: body
        name: job
        required: true
        schema:
          $ref: '#/definitions/jobs.Upload'
      produces:
      - application/json
      responses:
        "201":
          description: Job successfully created
          schema:
            $ref: '#/definitions/jobs.Job'
        "400":
          description: Bad request - validation error
          schema:
            $ref: '#/definitions/errors.RestErr'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/errors.RestErr'
      summary: Upload a new job to the queue
swagger: "2.0"
